services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console (web UI)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data  # Persistent storage

  hive-metastore-db:
    image: postgres:15
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - hive-metastore-db:/var/lib/postgresql/data

  hive-metastore:
    build:
      context: ..
      dockerfile: docker/hive/Dockerfile
    image: hive-custom:4.0.0
    hostname: hive-metastore
    environment:
      SERVICE_NAME: metastore
      DB_DRIVER: postgres
      DB_HOST: hive-metastore-db
      DB_PORT: 5432
      DB_NAME: metastore
      DB_USER: hive
      DB_PASSWORD: hive
      HIVE_METASTORE_WAREHOUSE_DIR: s3a://multisource-retail/warehouse
    ports:
      - "9083:9083"  # Metastore port for Spark/Trino
    volumes:
      - ../configs/hive/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ../configs/hive/hive-site.xml:/opt/hive/conf/hive-site.xml
    depends_on:
      - minio  # Wait for MinIO
      - hive-metastore-db

  spark:
    build:
      context: ..
      dockerfile: docker/spark/Dockerfile
    image: spark-custom:4.0.1
    hostname: spark
    user: root
    command: >
      sh -c "chown -R spark:spark /opt/data && exec su spark -c 'sleep infinity'"
    environment:
      - SPARK_MODE=master
      - PYSPARK_PYTHON=python3
    ports:
      - "4040:4040"
      - "4041:4041"
    volumes:
      - ../scripts:/opt/scripts  # Mount scripts
      - ../configs:/opt/configs # Mount configs
      - ../utils:/opt/utils # Mount utils
      - ../data:/opt/data # Mount data folder
      - ../sql:/opt/sql # Mount sql folder
      - ../configs/hive/hive-site.xml:/opt/spark/conf/hive-site.xml
      - ../configs/hive/hadoop/core-site.xml:/opt/spark/conf/core-site.xml
    depends_on:
      - minio
      - hive-metastore

  trino:
    image: trinodb/trino:428
    hostname: trino
    ports:
      - "8080:8080"  # Trino web UI and query port
    volumes:
      - ../configs/trino/catalog:/etc/trino/catalog  # Mount Trino configs
    depends_on:
      - hive-metastore

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
      image: confluentinc/cp-kafka:7.3.0
      hostname: kafka
      container_name: kafka
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
        - "29092:29092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

volumes: # Named volume for persistence
  minio-data:
  hive-metastore-db: